FROM balenalib/%%BALENA_MACHINE_NAME%%-python:latest
WORKDIR /usr/src/app
COPY requirements.txt requirements.txt
RUN apt-get update && apt-get -y install gcc python3-dev
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . ./
ENV UDEV=1
CMD ["python","-u","src/main.py"]